openapi: 3.0.0
info:
  title: The SoftSkills
  version: 1.0.0

tags:
  - name: Utilizadores
  - name: Categorização

paths:

  /utilizador:
    get:
      tags:
        - Utilizadores
      summary: Obter utilizador por email
      parameters:
        - name: email
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Um utilizador
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilizador'
        '400':
          description: Email is required
        '404':
          description: User not found
          
    post:
      tags:
        - Utilizadores
      summary: Criar utilizador
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                salt:
                  type: string
                passwordhash:
                  type: string
                morada:
                  type: string
                foto:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
                    example: 'admin'
                      
              required:
                - nome
                - email
                - salt
                - passwordhash
      responses :
        '200':
          description: Um utilizador
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilizador'
        '400':
          description: Email is required or Something bad happened
        '404':
          description: User not found
          
  /utilizador/id/{id}:
    get:
      tags:
        - Utilizadores
      summary: Obter utilizador por id
      parameters:
        - name: id
          in: path
          description: 'Id do utilizador'
          required: True
          schema:
            type: integer
      responses :
        '200':
          description: Um utilizador
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilizador'
        '400':
          description: Something bad happened
        '404':
          description: User not found
          
    post:
      tags:
        - Utilizadores
      summary: Atualizar utilizador
      parameters:
        - name: id
          in: path
          description: 'Id do utilizador'
          required: True
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                email:
                  type: string
                passwordhash:
                  type: string
                morada:
                  type: string
                foto:
                  type: string
                roles:
                  type: array
                  items:
                    type: string
                    example: 'admin'

      responses :
        '200':
          description: Um utilizador
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Utilizador'
        '500':
          description: 'Error updating User'
          
  /utilizador/delete/{id}:
    post:
      tags:
        - Utilizadores
      summary: Desativar utilizador
      parameters:
        - name: id
          in: path
          description: 'Id do utilizador'
          required: True
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                passwordhash:
                  type: string
                  example: '5a4364dceb1416d1117e0085b0f5af12a30fe3a4f7a503f8f40309324972ecb3309b690141837b1c3d9db8d5de8a172a3c05fe979ded9e90c30a8d70587b9c'
      responses :
        '200':
          description: 'User deactivated'
        '500':
          description: 'Missing passwordhash'
        '501':
          description: 'Password mismatch'
        '404':
          description: 'User not found'
          
  /utilizador/activate/{id}:
    post:
      tags:
        - Utilizadores
      summary: Ativar utilizador
      parameters:
        - name: id
          in: path
          description: 'Id do utilizador'
          required: True
          schema:
            type: integer
      responses :
        '200':
          description: 'User Activate'
        '500':
          description: 'Something bad happened'
      
    
  
  /categoria:
    post:
      tags:
        - Categorização
      summary: Criar categoria
      requestBody:
        content:
          application/json:
            schema:
                type: object
                properties:
                  designacao:
                    type: string
                    example: Tecnologia

      responses :
        '200':
          description: Uma Categoria
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
        '400':
          description: Something bad happened
          

  /categoria/list :
    get:
      tags:
        - Categorização
      summary: Obter todas as categorias
      responses :
        '200':
          description: Array de categorias
          content:
            application/json:
              schema:
                type: array
                items :
                  $ref: '#/components/schemas/Categoria'
        '400':
          description: Something bad happened
          
  /categoria/id/{id} :
    get:
      tags:
        - Categorização
      summary: Obter uma categoria
      parameters:
        - name: id
          in: path
          description: 'Id da categoria'
          required: True
          schema:
            type: integer
      responses :
        '200':
          description: Array de categorias
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
        '400':
          description: Something bad happened

  /categoria/delete/{id} :
    get:
      tags:
        - Categorização
      summary: Eliminar uma categoria
      parameters:
        - name: id
          in: path
          description: 'Id da categoria'
          required: True
          schema:
            type: integer
      responses :
        '200':
          description: Mensagem
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Category deleted
        '400':
          description: Something bad happened

components:
  schemas:
  
    Utilizador:
    
      type: object
      properties:
      
        idUtilizador:
          type: integer
          example: 3
          
        roles:
          type: array
          items: 
            type: object
            properties:
              idRole:
                type: integer
                example: 1
              role:
                type: string
                example: 'admin'
            
        nome:
          type: string
          example: 'Carlos Santos'
          
        email:
          type: string
          example: 'carlos.santos@email.com'
          
        salt:
          type: string
          example: 'c4e83f5caf2680e1'
          
        passwordhash:
          type: string
          example: '86304abeed0c35aa7e ...'
          
        dataregisto:
          type: string
          example: '2024-03-20'
          
        morada:
          type: string
          example: 'Travessa do Norte, 78'
          
        foto:
          type: string
          example: 'http://randomobjectstorage/bc9d7e181a996ea.jpg'
  
        

    

 
    Categoria :
      type: object
      properties :
        idCategoria :
          type : number
          example: 1
        designacao :
          type: string
          example : "Tecnologia"
          